//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMallManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Screening_seat = new HashSet<Screening_seat>();
        }
    
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public int Discount { get; set; }
        public double Total { get; set; }
        public int Screening_Id { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public int NumberOfSeats { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Screening Screening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Screening_seat> Screening_seat { get; set; }
    }
}
