//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMallManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screening_seat
    {
        public int ShowSeat_id { get; set; }
        public int Seat_IdSeat { get; set; }
        public int Screening_Id { get; set; }
        public int Order_OrderId { get; set; }
        public Nullable<bool> Status { get; set; }
        public double Price { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Screening Screening { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
